title: My Blog
description: My Personal Blog
author: Joshua Hull
github: https://github.com/joshua-hull
about: Software Developer in Greenville, SC
urls:
    - text: About Me
      url: /about/
    - text: "@joshua_hull"
      url: https://twitter.com/joshua_hull
    - text: Github
      url: https://github.com/joshua-hull
    - text: Online Resume
      url: /resumecard/
    - text: LinkedIn
      url: https://www.linkedin.com/in/joshua-hull-25551624
    - text: XML Feed
      url: /feed.xml
url: "https://joshua-hull.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
