title: My Blog
description: My Personal Blog
author: Joshua Hull
github: https://github.com/joshua-hull
about: Software Developer in Greenville, SC
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/joshua-hull
    - text: XML Feed
      url: /feed.xml
    - text: \@joshua_hull
      url: https://twitter.com/joshua_hull
url: "https://joshua-hull.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
